# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

missingSampler <- function() {
    .Call('_RERconverge_missingSampler', PACKAGE = 'RERconverge')
}

isNA <- function(x) {
    .Call('_RERconverge_isNA', PACKAGE = 'RERconverge', x)
}

isNotNArowvec <- function(x) {
    .Call('_RERconverge_isNotNArowvec', PACKAGE = 'RERconverge', x)
}

fastLmResid <- function(Y, X) {
    .Call('_RERconverge_fastLmResid', PACKAGE = 'RERconverge', Y, X)
}

fastLmPredicted <- function(Y, X) {
    .Call('_RERconverge_fastLmPredicted', PACKAGE = 'RERconverge', Y, X)
}

fastLmResidWeighted <- function(Y, X, wa) {
    .Call('_RERconverge_fastLmResidWeighted', PACKAGE = 'RERconverge', Y, X, wa)
}

fastLm <- function(Y, X) {
    .Call('_RERconverge_fastLm', PACKAGE = 'RERconverge', Y, X)
}

fastLmResidMat <- function(Y, X) {
    .Call('_RERconverge_fastLmResidMat', PACKAGE = 'RERconverge', Y, X)
}

fastLmPredictedMat <- function(Y, X) {
    .Call('_RERconverge_fastLmPredictedMat', PACKAGE = 'RERconverge', Y, X)
}

fastLmResidMatWeighted <- function(Y, X, W) {
    .Call('_RERconverge_fastLmResidMatWeighted', PACKAGE = 'RERconverge', Y, X, W)
}

fastLmResidMatWeightedNoNACheck <- function(Y, X, W) {
    .Call('_RERconverge_fastLmResidMatWeightedNoNACheck', PACKAGE = 'RERconverge', Y, X, W)
}

fastLmResidWeightedPredict <- function(Y, X, wa, newX) {
    .Call('_RERconverge_fastLmResidWeightedPredict', PACKAGE = 'RERconverge', Y, X, wa, newX)
}

fastLmResidMatWeightedPredict <- function(Y, X, W, newX) {
    .Call('_RERconverge_fastLmResidMatWeightedPredict', PACKAGE = 'RERconverge', Y, X, W, newX)
}

