# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call(`_RERconverge_timesTwo`, x)
}

missingSampler <- function() {
    .Call(`_RERconverge_missingSampler`)
}

isNA <- function(x) {
    .Call(`_RERconverge_isNA`, x)
}

isNotNArowvec <- function(x) {
    .Call(`_RERconverge_isNotNArowvec`, x)
}

fastLmResid <- function(Y, X) {
    .Call(`_RERconverge_fastLmResid`, Y, X)
}

fastLmPredicted <- function(Y, X) {
    .Call(`_RERconverge_fastLmPredicted`, Y, X)
}

fastLmResidWeighted <- function(Y, X, wa) {
    .Call(`_RERconverge_fastLmResidWeighted`, Y, X, wa)
}

fastLm <- function(Y, X) {
    .Call(`_RERconverge_fastLm`, Y, X)
}

fastLmResidMat <- function(Y, X) {
    .Call(`_RERconverge_fastLmResidMat`, Y, X)
}

fastLmPredictedMat <- function(Y, X) {
    .Call(`_RERconverge_fastLmPredictedMat`, Y, X)
}

fastLmResidMatWeighted <- function(Y, X, W) {
    .Call(`_RERconverge_fastLmResidMatWeighted`, Y, X, W)
}

fastLmResidMatWeightedNoNACheck <- function(Y, X, W) {
    .Call(`_RERconverge_fastLmResidMatWeightedNoNACheck`, Y, X, W)
}

